version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=5466
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5466:5432"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.18.0.0/16




volumes:
  postgres-data:
